### ISSUE TITLE
Add config option to generate minify static pages

### ISSUE THREAD

**Issue by gbrlmrllo** [plopcas/hugo-s3-action#1]
It would be good if when [generating the static pages](https://github.com/plopcas/hugo-s3-action/blob/master/entrypoint.sh#L47) we could pass the `--minify` flag to it in order to optimize the generated files.

**Comment by plopcas** [comment]
Thanks for the suggestion @gbrlmrllo , I have now added this feature in v1.4.0 👍

**Comment by gbrlmrllo** [comment]
ohh that's was quick, thanks!!!
