### ISSUE TITLE
`hugo deploy` deploys a fraction of necessary files

### ISSUE THREAD

**Issue by dgrebb** [plopcas/hugo-s3-action#3]
Howdy!

Could be user error. When I run `hugo` then `hugo deploy` locally, everything is uploaded to S3 as expected. Upon running this action in Github, Hugo deletes everything and only uploads a fraction of the files I'm expecting:

```
Identified 4 file(s) to upload, totaling 2.1 kB, and 38 file(s) to delete.
```

What am I doing wrong?

Cheers,
Dan

**Comment by plopcas** [comment]
Thanks for reaching out. Closing as this is not directly related to this action specifically.
